buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }


        dependencies {
            classpath "com.android.tools.build:gradle:8.1.3" // 🔥o Update this line
            classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.0" // ✅ Kotlin 2.1.0
            classpath "com.google.gms:google-services:4.4.0" // Firebase
        }


}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
configurations.all {
    resolutionStrategy.force 'androidx.credentials:credentials:1.2.0-rc01'
}